# Generated by Django 2.2.5 on 2019-11-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communities',
            name='Description',
            field=models.TextField(default='None', max_length=250),
        ),
    ]
