# Generated by Django 2.2.5 on 2019-11-01 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communities', '0004_auto_20191031_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communities',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='communities',
            old_name='User',
            new_name='Users',
        ),
        migrations.AddField(
            model_name='communities',
            name='Admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communities',
            name='Created_on',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
