# Generated by Django 2.2.5 on 2019-11-01 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Communities', '0005_auto_20191031_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communities',
            name='Admin',
        ),
    ]
