# Generated by Django 2.2.5 on 2019-11-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communities', '0007_auto_20191104_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='Image',
            field=models.ImageField(default='defaultAvatar.png', upload_to='community_pics'),
        ),
    ]
