# Generated by Django 2.2.5 on 2019-11-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communities', '0008_auto_20191110_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='Image',
            field=models.ImageField(default='community_pics/defaultAvatar.png', upload_to='community_pics'),
        ),
    ]
