# Generated by Django 2.2.5 on 2019-11-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communities', '0009_auto_20191110_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='Image',
            field=models.ImageField(default='media/community_pics/defaultAvatar.png', upload_to='community_pics'),
        ),
    ]
