# Generated by Django 2.2.5 on 2019-10-14 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'Questions'},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='QuestionField',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Title',
            new_name='Question',
        ),
    ]
