# Generated by Django 2.2.5 on 2019-10-14 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_auto_20191009_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='QuestionField',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Title',
            new_name='Question',
        ),
    ]
