# Generated by Django 2.2.5 on 2019-10-21 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_auto_20191014_1628'),
        ('Questions', '0002_auto_20191014_1650'),
    ]

    operations = [
    ]
