# Generated by Django 2.2.5 on 2019-10-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_auto_20191014_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Subject',
            field=models.CharField(default='Math', max_length=16),
            preserve_default=False,
        ),
    ]
