# Generated by Django 2.2.5 on 2019-11-04 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_auto_20191014_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Profile'),
        ),
    ]
