# Generated by Django 2.2.5 on 2019-11-15 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20191018_2342'),
        ('Questions', '0004_auto_20191104_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Response', models.CharField(max_length=10000)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.Question')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Profile')),
            ],
        ),
    ]
