# Generated by Django 2.2.5 on 2019-11-01 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0004_merge_20191021_1642'),
        ('Questions', '0004_question_subject'),
    ]

    operations = [
    ]
