# Generated by Django 2.2.5 on 2019-11-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0005_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Subject',
            field=models.CharField(default='Math', max_length=20),
            preserve_default=False,
        ),
    ]
