# Generated by Django 2.2.5 on 2019-11-16 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0005_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Created_on',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
