# Generated by Django 2.2.5 on 2019-11-18 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0006_question_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'verbose_name_plural': 'Responses'},
        ),
    ]
