# Generated by Django 2.2.5 on 2019-11-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0007_auto_20191118_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={},
        ),
    ]
