# Generated by Django 2.2.5 on 2019-11-20 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0008_auto_20191118_1254'),
        ('Questions', '0006_question_subject'),
    ]

    operations = [
    ]
