# Generated by Django 2.2.5 on 2019-11-01 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StorePage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
